In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Import dataset
ds = pd.read_csv("Data.csv")
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [7]:
print(y)
y = y.reshape(len(y),1)
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [12]:
# Split dataset into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
sc_X.fit_transform(X_train)
sc_y.fit_transform(y_train)


array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [26]:
# Training the SVM
from sklearn.svm import SVR
regressor = SVR()
regressor.fit(X_train, y_train)

C:\Users\yohan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [27]:
# Predicting values and determining R squared value
from sklearn.metrics import r2_score
y_pred = regressor.predict(X_test)
r2_score(y_test, y_pred)


0.38182110451293594