In [115]:
# Import libraries
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import tensorflow as tf 
print(tf.__version__)

2.18.0


In [117]:
# Import dataset
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values 
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [119]:
# Encoding categorical data 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
label = LabelEncoder()
X[:, 2] = label.fit_transform(X[:, 2])
print(X[:, 2])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))




[0 0 0 ... 0 1 0]


In [66]:
# Split into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [68]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [70]:
# initializing artificial neural network 
ann = tf.keras.models.Sequential()

In [72]:
# Creating input layer and two hidden layers
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [74]:
# Adding output layer 
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [76]:
# Compiling and training the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size =3, epochs = 100)



Epoch 1/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7354 - loss: 0.5598
Epoch 2/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8213 - loss: 0.4180
Epoch 3/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8250 - loss: 0.4090
Epoch 4/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8519 - loss: 0.3665
Epoch 5/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8562 - loss: 0.3568
Epoch 6/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8546 - loss: 0.3529
Epoch 7/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8632 - loss: 0.3471
Epoch 8/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8596 - loss: 0.3512
Epoch 9/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8643 - loss: 0.3321
Epoch 10/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8566 - loss: 0.3411
Epoch 11/100
2667/2667 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8564 - loss: 0.3495
Epoch 12/100
2667/2

### Predicting a result
test = [[600, 'France', 1, 40, 3, 60000, 2, 1, 1, 50000 ]]
print(test)
ann.predict(ct.transform(test))

In [138]:
# Predicting a result. Could have just entered the categorical dummy variables for France
test = [[600, 'France', 1, 40, 3, 60000, 2, 1, 1, 50000 ]] 
print(ct.transform(test)) 
y_pred = ann.predict(sc.transform(ct.transform(test)))

[[1.0 0.0 0.0 600 1 40 3 60000 2 1 1 50000]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


In [140]:
print(y_pred > 0.5)

[[False]]


In [158]:
# Predict and compare test results
y_pred = ann.predict(X_test) > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [170]:
# Confusion matrix and accuracy score 
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))

[[1519  193]
 [  76  212]]
0.8655
